from pathlib import Path

from points.progressions.levels.levels import (
    get_points_required_for_next_level,
    get_total_points_required_for_level,
)

from points.progressions.ranks.ranks import (
    RANKS,
    get_rank_for_level,
)


# ==================================================
# CONFIGURATION
# ==================================================


# Levels are unlimited, so this determines how many
# levels are included in the human-readable reference.
REFERENCE_MAX_LEVEL = 150


# The generated reference is placed in the same
# folder as this file.
OUTPUT_PATH = Path(__file__).with_name(
    "progressions_reference.md"
)


# ==================================================
# RANK TABLE
# ==================================================


def build_rank_table() -> str:
    """
    Build a Markdown table showing the generated
    level and point requirements for every rank.
    """

    lines = [
        "# M.A.R.T.Y. Progressions Reference",
        "",
        "This file is automatically generated when M.A.R.T.Y. starts.",
        "",
        "Do not manually edit this file.",
        "",
        "## Rank Progression",
        "",
        (
            "| Tier | Rank | Level Range | "
            "Start Points | End Points | Points in Rank |"
        ),
        "|---:|---|---:|---:|---:|---:|",
    ]

    for rank in RANKS:

        tier = rank[
            "tier"
        ]

        name = rank[
            "name"
        ]

        start_level = rank[
            "start_level"
        ]

        end_level = rank[
            "end_level"
        ]

        start_points = (
            get_total_points_required_for_level(
                start_level
            )
        )

        # ------------------------------------------
        # FINAL UNLIMITED RANK
        # ------------------------------------------

        if end_level is None:

            level_range = (
                f"{start_level}+"
            )

            end_points_display = (
                "Unlimited"
            )

            points_in_rank_display = (
                "Unlimited"
            )

        # ------------------------------------------
        # NORMAL RANK
        # ------------------------------------------

        else:

            level_range = (
                f"{start_level}-{end_level}"
            )

            next_rank_start_points = (
                get_total_points_required_for_level(
                    end_level + 1
                )
            )

            end_points = (
                next_rank_start_points - 1
            )

            points_in_rank = (
                next_rank_start_points
                - start_points
            )

            end_points_display = (
                f"{end_points:,}"
            )

            points_in_rank_display = (
                f"{points_in_rank:,}"
            )

        lines.append(
            f"| {tier} "
            f"| {name} "
            f"| {level_range} "
            f"| {start_points:,} "
            f"| {end_points_display} "
            f"| {points_in_rank_display} |"
        )

    return "\n".join(
        lines
    )


# ==================================================
# LEVEL TABLE
# ==================================================


def build_level_table() -> str:
    """
    Build a Markdown table showing the generated
    point requirements for each displayed level.
    """

    lines = [
        "",
        "## Level Progression",
        "",
        (
            "| Level | Rank | Start Points | "
            "End Points | Points to Next Level |"
        ),
        "|---:|---|---:|---:|---:|",
    ]

    for level in range(
        1,
        REFERENCE_MAX_LEVEL + 1,
    ):

        rank = get_rank_for_level(
            level
        )

        start_points = (
            get_total_points_required_for_level(
                level
            )
        )

        points_required = (
            get_points_required_for_next_level(
                level
            )
        )

        end_points = (
            start_points
            + points_required
            - 1
        )

        lines.append(
            f"| {level} "
            f"| {rank['name']} "
            f"| {start_points:,} "
            f"| {end_points:,} "
            f"| {points_required:,} |"
        )

    return "\n".join(
        lines
    )


# ==================================================
# GENERATE REFERENCE
# ==================================================


def generate_progressions_reference():
    """
    Generate and overwrite the progression
    reference Markdown file.

    The contents are generated entirely from the
    current rank and level configuration.
    """

    contents = (
        build_rank_table()
        + "\n"
        + build_level_table()
        + "\n"
    )

    OUTPUT_PATH.write_text(
        contents,
        encoding="utf-8",
    )

    print(
        "Progressions reference updated: "
        f"{OUTPUT_PATH}"
    )


# ==================================================
# RUN DIRECTLY
# ==================================================


if __name__ == "__main__":
    generate_progressions_reference()